// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "navbar": {
    "logo": "Logo",
    "charity_projects": "Charity Projects",
    "donation_methods": "Donation Methods",
    "sections": "Sections",
    "section1": "Section One",
    "section2": "Section Two",
    "about_us": "About Us",
    "about_page": "About the Organization",
    "contact_us": "Contact Us",
    "search_placeholder": "Search...",
    "login": "Login",
    "login_description": "Enter your credentials to access your account.",
    "username": "Username",
    "password": "Password",
    "menu": "Menu"
  },
  "home": {
    "hero": {
      "bismillah": "In the name of Allah, the Most Gracious, the Most Merciful",
      "verse": "مَثَلُ الَّذِينَ يُنْفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ كَمَثَلِ حَبَّةٍ أَنْبَتَتْ سَبْعَ سَنَابِلَ فِي كُلِّ سُنْبُلَةٍ مِائَةُ حَبَّةٍ وَاللَّهُ يُضَاعِفُ لِمَنْ يَشَاءُ وَاللَّهُ وَاسِعٌ عَلِيمٌ",
      "donate_button": "Register & Donate",
      "browse_projects_button": "Browse Projects"
    },
    "stats": {
      "transparency_label": "Transparency",
      "transparency_text": "Complete & Documented",
      "donation_methods_label": "15 Ways",
      "donation_methods_text": "Of Donation",
      "charities_label": "More than",
      "charities_text": "50 Charities",
      "projects_label": "152",
      "projects_text": "Active Projects"
    },
    "charities": {
      "title_part1": "Charity",
      "title_part2": "Organizations",
      "subtitle": "Registered charity organizations on our platform"
    },
    "projects": {
      "title_part1": "Current",
      "title_part2": "Projects",
      "view_all": "All Projects",
      "from": "of",
      "currency": "EGP",
      "categories": {
        "all": "All",
        "food": "Food",
        "health": "Health",
        "marriage": "Marriage",
        "charity": "Charity"
      },
      "project1": {
        "title": "Ramadan Food Campaign for Families in Rural Egypt."
      },
      "project2": {
        "title": "Medical Treatment Campaign for Those in Need"
      },
      "project3": {
        "title": "Marriage Support for Young People"
      },
      "project4": {
        "title": "Building a Mosque in a Remote Village"
      },
      "charities": {
        "resala": "Resala Charity",
        "orman": "Al-Orman Association",
        "mek": "Misr El Kheir Foundation",
        "mersal": "Mersal Foundation"
      }
    }
  },
  "footer": {
    "all_rights_reserved": "All rights reserved to Mabit Thawab",
    "tax_id": "Tax ID",
    "site_name": ""
  }
};
export default messages;